### PR TITLE
Fix shapely deprecation warnings and remove descartes dependency

### PR DESCRIPTION
**Pull request by fmaussion**

### CODE REVIEW

**Comment by fmaussion** [comment]
@TimoRoth any idea what's going on with coveralls again? Do we have a way to get the tests green even if coveralls has a hickup maybe?

**Comment by fmaussion** [comment]
Ah OK that's the issue: https://github.com/TheKevJames/coveralls-python/issues/333

**Comment by fmaussion** [comment]
closes https://github.com/fmaussion/salem/issues/211

**Comment by jorisvandenbossche** [comment]
FYI, you could slim down the "vendored" file with descartes' code quite a bit, if you wanted, see https://github.com/geopandas/geopandas/issues/1039#issuecomment-748625852 (which is what we did in geopandas: https://github.com/geopandas/geopandas/blob/831108dcb369517e311cd0ee3821db1f2fb7122d/geopandas/plotting.py#L100-L123)

**Comment by fmaussion** [comment]
Thanks a lot for the heads up @jorisvandenbossche ! Much appreciated

**Pull request merged**
