### PR TITLE
Migrate from Travis to Github Actions

### PR DESCRIPTION
**Pull request by TimoRoth**
Should behave the same.
Also updated the tests to py38 where applicable.

The old pyproj version of the tests does not seem to work anymore.

### CODE REVIEW

**Comment by fmaussion** [comment]
Yes I think its ok to stop suppoting the old pyproj now. If I recall I put it on the allowed failures last time I worked on it

**Comment by fmaussion** [comment]
Will the tests run only after merge? At the moment I can't see anything...

**Comment by TimoRoth** [comment]
You can look at them in my repo, they won't run here until the workflow file is merged.

**Comment by fmaussion** [comment]
Awesome! Can I merge then?

**Comment by TimoRoth** [comment]
If there's nothing you want changed, go ahead.

**Pull request merged**
