### PR TITLE
Workflow updates and artifact uploads

### PR DESCRIPTION
**Pull request by TimoRoth**

### CODE REVIEW

**Comment by fmaussion** [comment]
Is it expected that all tests are red?

**Comment by TimoRoth** [comment]
Given they all fail with the same two google maps tests failing with a 403, and neither PRs nor my Repo having access to the maps key, I'd say so.

**Comment by TimoRoth** [comment]
Wait, the non-mpl ones fail with a different error about not knowing the mpl argument. Which makes sense.
Need to think of a way to solve that, hm.

**Comment by fmaussion** [comment]
> Given they all fail with the same two google maps tests failing with a 403, and neither PRs nor my Repo having access to the maps key, I'd say so.

Still, something is wrong with this because the tests should be skipped if no key is provided

**Comment by fmaussion** [comment]
That was the purpose of `requires_static_key` - will have to look into this when the other tests are green.

**Comment by TimoRoth** [comment]
Seems like you just forgot the two gmaps-using tests in test_datasets.py.

**Pull request merged**
